services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8"
      TZ: Asia/Tokyo
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: db3306
      TZ: Asia/Tokyo
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: db3307
      TZ: Asia/Tokyo
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  memcached:
    image: memcached 
    restart: always
    ports:
      - 11211:11211
  bigquery:
    image: ghcr.io/goccy/bigquery-emulator
    restart: always
    ports:
      - 9050:9050
    command: "bigquery-emulator --project=local-bigquery --dataset=dataset1"
  gcs:
    image: fsouza/fake-gcs-server
    restart: always
    ports:
      - 4443:4443
    command: "-scheme http -public-host localhost"
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    restart: always
    ports:
      - 9010:9010
      - 9020:9020
